### ISSUE TITLE
Documentation update for "manage-stack" helper script

### ISSUE THREAD

**Issue by yguntaka** [aws-samples/vpn-gateway-strongwswan#11]
The REGION parameter in manage-stack is set to us-east-2.
Update notes in README that users need to set the appropriate region in line 81 for REGION=< > if it needs to be other than us-east-2

**Comment by ckamps** [comment]
@yguntaka - Thanks for filing this issue. I've updated the README.md to document the common option arguments for the `manage-stack` wrapper script. Please review it and let me know if it doesn't address this issue.

**Comment by yguntaka** [comment]
Thank you for the prompt update @ckamps 
I created a new vpnstack with your updates and work great. This solution has been super helpful to play around with strongswan and quagga. Cheers!

**Comment by yguntaka** [comment]
Region is now an option to call manage-stack, else defaults to the user's region from profile.
./manage-stack -e mystack1 --region us-east-1 template-parameters-psk-auth.json
