### ISSUE TITLE
Parameterize PSK Secret Key Region

### ISSUE THREAD

**Issue by ASingletonOfCode** [aws-samples/vpn-gateway-strongwswan#13]
The recent change to use Secrets Manager for fetching the PSKs defaults to US-East-2. Please create a parameter or mention this in prerquisites. This causes the stack create to fail if you're not using US-East-2.

https://github.com/aws-samples/vpn-gateway-strongwswan/blob/b090ae222e1f6813cc1a0faffa29a2b0fd1bd7e3/vpn-gateway-strongswan.yml#L760

**Comment by techdad** [comment]
https://github.com/aws-samples/vpn-gateway-strongwswan/pull/14

This PR fixes it.

**Comment by ckamps** [comment]
Thanks!
